# Generated by Django 2.2 on 2021-09-16 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokerboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Name of Pokerboard', max_length=20, unique=True)),
                ('description', models.CharField(help_text='Description', max_length=100)),
                ('estimation_type', models.IntegerField(choices=[(1, 'Series'), (2, 'Even'), (3, 'Odd'), (4, 'Fibonacci')], default=1, help_text='Estimation type')),
                ('duration', models.IntegerField(help_text='Duration for voting (in secs)')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Created'), (2, 'Started'), (3, 'Ended')], default=1)),
                ('manager', models.ForeignKey(help_text='Owner of Pokerboard', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_id', models.SlugField(help_text='Ticket ID imported from JIRA')),
                ('estimate', models.IntegerField(help_text='Final estimate of ticket', null=True)),
                ('rank', models.PositiveSmallIntegerField(help_text='Rank of ticket')),
                ('pokerboard', models.ForeignKey(help_text='Pokerboard to which ticket belongs', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='pokerboard.Pokerboard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField(choices=[(1, 'email'), (2, 'group')], default=1, help_text='Invited through')),
                ('invitee', models.EmailField(help_text='Person invited', max_length=254, null=True)),
                ('group_name', models.CharField(help_text='Name of group', max_length=20, null=True)),
                ('role', models.IntegerField(choices=[(1, 'Spectator'), (2, 'Contributor')], default=2, help_text='Role')),
                ('is_accepted', models.BooleanField(default=False, help_text='Accepted or not?')),
                ('group', models.ForeignKey(help_text='Name of group through which invited, if invited via group', null=True, on_delete=django.db.models.deletion.CASCADE, to='group.Group')),
                ('pokerboard', models.ForeignKey(help_text='Pokerboard', on_delete=django.db.models.deletion.CASCADE, related_name='invite', to='pokerboard.Pokerboard')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
