# Generated by Django 2.2 on 2021-09-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='is_accepted',
            field=models.BooleanField(default=False, help_text='Boolean indicates if invitation accepted or not'),
        ),
    ]
