# Generated by Django 2.2 on 2021-09-17 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pokerboard', '0002_auto_20210916_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveIntegerField(choices=[(1, 'In progress'), (2, 'Skipped'), (3, 'Estimated')], default=1)),
                ('timer_started_at', models.DateTimeField(null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimations', to='pokerboard.Ticket')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimate', models.PositiveIntegerField()),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='pokerboard.GameSession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'game_session')},
            },
        ),
    ]
